#!/bin/sh

# Adds daily trending repositories to pending list

set -e

URL="https://github.com/trending"
curl -s "$URL" |
    grep 'data-hydro-click' |
    grep 'TRENDING_REPOSITORIES_PAGE' |
    grep -oE 'href="/[^/"]*/[^"]*' |
    awk -F'"' '{print "https://github.com"$2}' |
    while read -r repo; do
        grep -q "$repo" pending || echo "$repo"
    done >/tmp/trending-repos

if ! grep -q . /tmp/trending-repos ; then
    echo "No new trending repositories found"
    exit 0
fi

cat /tmp/trending-repos |
    head -n4 | # increase/decrease `head` count to control how many trending items we add
    while read -r repo; do
        stars="$(curl -s "$repo" | pup '.js-social-count attr{aria-label}' |
            grep 'starred this repository' | cut -d' ' -f1)"
        [ -n "$stars" ] && [ $stars -le 50 ] && continue
        echo "- $repo" >>pending
    done
