#!/bin/sh

set -e

URL="https://github.com/trending"
curl "$URL" |
	grep 'data-hydro-click' |
	grep 'TRENDING_REPOSITORIES_PAGE' |
	grep -o 'href="[^"]*' |
	head -n1 |
	awk -F'"' '{print "https://github.com"$2}' > repo
