#!/bin/sh

set -e


# cat eapi | jq -r '.[0].url' | grep -Eo '[^\/]*/[^\/]*$'

curl 'https://ghapi.huchen.dev/repositories?since=daily' | 
    grep -Eo '"url": ?"https://github.com[^"]*"' | 
    grep -Eo '[^\/]*/[^\/]*"$' | sed 's|"$||' | head -n1 > repo
