#!/bin/sh

rm -f /results/{gource.ppm,gource.mp4}
RES="${RES:-1280x720}"
DEPTH="${DEPTH:-24}"

xvfb-run -a -s "-screen 0 ${RES}x${DEPTH}" /tmp/qg &

lastsize=0
filesize=0
while true;do
    sleep 20
    lastsize="$filesize" && filesize="$(stat -c '%s' /results/gource.mp4)"
    echo 'Polling the size. Current size is' "$filesize"
    [ "$filesize" -ne "0" ] && [ "$lastsize" -eq "$filesize" ] && break
done
echo "Force stopping..."
pkill -SIGKILL gource
sleep 30 # wait for ffmpeg to finish (>20 as ffmpeg timeout is 20)
