#!/bin/sh


wget 'https://github.com/porjo/youtubeuploader/releases/download/20.04/youtubeuploader_linux_amd64.tar.gz' 
tar -xvzf youtubeuploader_linux_amd64.tar.gz
echo "$CLIENT_SECRETS" > client_secrets.json
echo "$REQUEST_TOKEN" > request.token

RES="${RES:-1920x1080}"
echo "Starting video generation..."
gource -s 0.2 -a 1 ./ -"$RES" -o - |
ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset medium \
-timeout 20 \
-pix_fmt yuv420p -crf 1 -analyzeduration 999999999 -probesize 999999999 -threads 0 -bf 0 -f mpegts - |
pv -f 2>/results/gource |
./youtubeuploader_linux_amd64 -filename - \
-title "Gource visualisation: $(head repo) on $(date '+%Y-%m-%d')" \
-description "https://github.com/$(head repo) built using https://github.com/meain/gourcer" -privacy public
