#!/bin/bash

set -e

# If someone stars of forks this weird repo, the tests will fail
# But I am pretty sure no one will. Just gonna go with it for now.

cp tests/repo repo
rm -rf crepo
git clone "$(head repo)" crepo
./gstats > description && cat description
diff <(head -n12 description) <(head -n12 tests/description) 
