#!/bin/sh

# running the separtely without getpending so as to make sure it runs
git config --global user.email "bot@meain.io"
git config --global user.name "Bot"

git add pending

if [ -z "$1" ]; then
    git commit -m "Ran $(head repo)

$(grep -Ec '^-' pending)/$(grep -c . pending) items remaining. [~$(($(grep -Ec '^-' pending) / 4))d]"
else
    git commit -m "$1"
fi
git push origin master
