name: Add trending repositories

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update trending
        run: |
          ./add-trending
          ./commit-pending-list 'Update trending repositories'
