name: Test gh description generation

on:
  push:
    branches:
      - master
  schedule:
    - cron: "10 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: ./scripts/test
