name: update-trending

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Daily pull
        run: ./daily
      - name: Mark completion
        run: ./updatepending '[trending]'
